/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd_udp;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author paulo
 */
public class JanelaMensagem extends javax.swing.JFrame {

    private Thread segundaThread;
    private DatagramSocket s;
    private InetAddress dest;
    DatagramPacket datagramPacket;

    /**
     * Creates new form JanelaMensagem
     */
    public JanelaMensagem() throws SocketException, UnknownHostException {
        this.dest = InetAddress.getByName("localhost");
        this.s = new DatagramSocket();
        
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                digiteAqui.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        String envio = digiteAqui.getText();
                        
                        if (envio.equalsIgnoreCase("")) {// Cliente disse que quer sair. HAHA
                            envio = Constants.LOGOUT;
                        }
                        //Envio de mensagem
                        try {
                            byte[] buffer = envio.getBytes();
                            datagramPacket = new DatagramPacket(buffer, buffer.length, dest, 4545);
                            s.send(datagramPacket);
                            digiteAqui.setText("");
                        } catch (IOException ex) {
                            Logger.getLogger(JanelaMensagem.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
            }
        });

        //thread de resposta
        segundaThread = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        DatagramPacket resposta = new DatagramPacket(new byte[512], 512);
                        s.receive(resposta);
                        String printResposta = new String(resposta.getData());
                        
                        //VERIFICANDO SE O CARA QUER SAIR...
                        if (resposta.getSocketAddress().equals(datagramPacket.getSocketAddress())) {
                            if (printResposta.trim().startsWith(Constants.LOGOUT)) {
                                System.exit(0);
                            }
                        }
                        
                        String texto = mensagens.getText();
                        texto = texto + printResposta+"\n";
                        mensagens.setText(texto);
                        
                    } catch (IOException ex) {
                        Logger.getLogger(JanelaMensagem.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });

        segundaThread.start();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digiteAqui = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensagens = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        digiteAqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digiteAquiActionPerformed(evt);
            }
        });

        mensagens.setEditable(false);
        mensagens.setColumns(20);
        mensagens.setRows(5);
        jScrollPane1.setViewportView(mensagens);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel1.setText("Instruções: Entrar no Chat digite: @ - Sair do Chat: Aperte espaço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(digiteAqui)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(digiteAqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void digiteAquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digiteAquiActionPerformed

    }//GEN-LAST:event_digiteAquiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaMensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JanelaMensagem().setVisible(true);
                } catch (SocketException ex) {
                    Logger.getLogger(JanelaMensagem.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(JanelaMensagem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField digiteAqui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mensagens;
    // End of variables declaration//GEN-END:variables
}
